### ISSUE TITLE
Prompt selecting a webhook instead of requiring a webhook link

### ISSUE THREAD

**Issue by Snazzah** [trello-talk/TrelloBot#11]
Instead of requiring a link to make a webhook connection, just prompt the server's webhooks and select one OR create one from scratch

**Comment by Coolguy3289** [comment]
Could just declare the channel desired, and let it create the webhook that way.

**Comment by Yamboy1** [comment]
This is an idea that I have been thinking about for a while, I'll get onto it when I get time

**Comment by Yamboy1** [comment]
@Coolguy3289 Should this be the default option, with the explicit webhook url option "for experts"

**Comment by Coolguy3289** [comment]
Yes, Let the channel name be what is in help text context, and in the details add the explanation to use a pre-defined Webhook. This could also prevent dupe webhooks on accident

**Comment by Snazzah** [comment]
This was added in the rewrite [here](https://github.com/trello-talk/TrelloBot/commit/5890e54ae77984a8fd4ac65ea743be0b87628178#diff-744e085136a2a8878f05182630c477d3).
