### ISSUE TITLE
Add comment to card

### ISSUE THREAD

**Issue by Yamboy1** [trello-talk/TrelloBot#15]
There's surprisingly no command to add a comment to a card, so this needs to be added.

**Comment by Snazzah** [comment]
While I was using the user bot to do actions on so I pretty much didn't think of making comments since I didn't have a clear way of showing who did what (it's pretty easy now but eh)

**Comment by Snazzah** [comment]
Added on rewrite: https://github.com/trello-talk/TrelloBot/commit/bba242941e69cf9ca7c69e3aabb3952d1a06c178
