### ISSUE TITLE
Add image preview to card changes hook

### ISSUE THREAD

**Issue by DavidJindie75** [trello-talk/TrelloBot#18]
Enable the cards image (cover?) to be shown when the card is changed,  eg; card moved

currently when a card is changed not only does it show the person who changed it,  but also their profile picture,  which could in turn be changed to the cover-  thanks !

**Comment by Snazzah** [comment]
if you mean card cover by the first image attachment put onto a card then maybe? I don't know if attachments are sent within card data when a webhook event is given from trello

**Comment by Snazzah** [comment]
Only `ADD_ATTACHMENT_TO_CARD` returns an image, so it is included in the rewrite here: https://github.com/trello-talk/TrelloBot/commit/42249a1

Regarding displaying the card cover in other card-related events, Trello does not return the cover in it's webhook requests. From #2:
> ... I would rather not make any additional requests to Trello while parsing the event.
