### ISSUE TITLE
Filter events by labels

### ISSUE THREAD

**Issue by yooksi** [trello-talk/TrelloBot#2]
Currently there are not filters that can be applied to the incoming feed. The most basic filter would be to filter the reported events by card labels. For example, if there are 3 labels on the board (red, green and blue) we would be able to configure the bot to include events that involve one or more of those labels while ignoring others.

The current way to do this is to setup a new board, subscribe the bot to that board and then copy and update**only relevant** cards to that board which the bot would then pickup.

**Comment by Snazzah** [comment]
Trello does not return any labels on cards unless its an event specifically about adding/removing labels from cards. I would rather not make any additional requests to Trello while parsing the event.
