### ISSUE TITLE
Assign roles with lower rights than admin 

### ISSUE THREAD

**Issue by k-ibr** [trello-talk/TrelloBot#27]
So users can use certain commands, and have no access to others.

**Comment by Snazzah** [comment]
In #40 
> As far as the bot goes towards functionality, the bot can really do as much as the user can via Trello so this feature wouldn't be all that necessary.

If you are talking about managing webhooks, then only give the role to users you want to have set up. At the moment, not having the `Trello` role prevents you from editing your own boards in your server, this may change in the rewrite so people with the `Trello` role will be restricted to *just* server-related changes (webhooks, server locale, etc.)
