### ISSUE TITLE
Feature Request: Allow specific actions by Discord role.

### ISSUE THREAD

**Issue by Trekkan** [trello-talk/TrelloBot#40]
It would be nice if we could limit what a user can do with specific Discord roles. 

As an example, I would like my users to be able to create a new card, but that's it.  I'm using this so members can submit bug reports or feature requests for an application.  But I don't want them to do much else with the board.

For now, we're manually adding in the new cards as we see members come up with bugs and feature requests.  But this could open up a lot more possibilities for customization as well. =)

**Comment by Snazzah** [comment]
As far as the bot goes towards functionality, the bot can really do as much as the user can via Trello (if not more) so this feature wouldn't be all that nessessary.
