### ISSUE TITLE
Handle ratelimits for Trello

### ISSUE THREAD

**Issue by Snazzah** [trello-talk/TrelloBot#45]
Use https://www.npm.im/bottleneck
- Has clustering

### ~~Discord~~
Ratelimits: https://discord.com/developers/docs/topics/rate-limits
Headers only show on POST events
Eris can post to discord webhooks with ratelimiting already

### Trello
Trello API rate limit docs: https://help.trello.com/article/838-api-rate-limits
> To help prevent strain on Trello’s servers, our API imposes rate limits per API key for all issued tokens. There is a limit of 300 requests per 10 seconds for each API key and no more than 100 requests per 10 second interval for each token. If a request exceeds the limit, Trello will return a 429 error.

#### Ratelimit headers
`x-rate-limit-api-token-interval-ms` 10000
`x-rate-limit-api-token-max` 100
`x-rate-limit-api-token-remaining` 99
`x-rate-limit-api-key-interval-ms` 10000
`x-rate-limit-api-key-max` 300
`x-rate-limit-api-key-remaining` 299
`x-rate-limit-member-interval-ms` 10000
`x-rate-limit-member-max` 200
`x-rate-limit-member-remaining` 199

`x-rate-limit-member` might mean there is a 3rd bucket for each path (`/members`, `/boards`) but there is no header that really says when this shows up (not even in `access-control-expose-headers`) so this might be ignored.

**Comment by Coolguy3289** [comment]
@Snazzah Trello API rate limit docs: https://help.trello.com/article/838-api-rate-limits

**Comment by Coolguy3289** [comment]
"To help prevent strain on Trello’s servers, our API imposes rate limits per API key for all issued tokens. There is a limit of 300 requests per 10 seconds for each API key and no more than 100 requests per 10 second interval for each token. If a request exceeds the limit, Trello will return a 429 error."

**Comment by Snazzah** [comment]
Added in https://github.com/trello-talk/TrelloBot/commit/b4b8d961fd33c3b26bba13222fc5cc0b50df89ef
The ratelimit per token is fairly large so we might not need to deal with it.
