### ISSUE TITLE
Error when trying to use T!auth

### ISSUE THREAD

**Issue by LemonDrop1228** [trello-talk/TrelloBot#62]
I attempted to authenticate with Trello and received this error:
[https://i.imgur.com/qrs6Pnw.png](https://i.imgur.com/qrs6Pnw.png)

I used: T!auth [trello board id]

...and the bot gave me a link to follow to authenticate, which upon following the link resulted in this error.

**Comment by Yamboy1** [comment]
My recommendation is to try it again, not sure what happened there, but it should work now.

**Comment by Snazzah** [comment]
Fixed
